# Generated by Django 3.0.4 on 2020-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='currency',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
